/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.40 from the
 * contents of ARP.xs. Do not edit this file, edit ARP.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "ARP.xs"
/*
Perl ARP Extension
Create and send an arp packets, lookup mac addresses

Programmed by Bastian Ballmann
Last update: 11.05.2022

This program is free software; you can redistribute 
it and/or modify it under the terms of the 
GNU General Public License version 2 as published 
by the Free Software Foundation.

This program is distributed in the hope that it will 
be useful, but WITHOUT ANY WARRANTY; without even 
the implied warranty of MERCHANTABILITY or FITNESS 
FOR A PARTICULAR PURPOSE. 
See the GNU General Public License for more details. 
*/

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"
#include <stdio.h>           
#include <stdlib.h>          
#include <string.h>          
#include <errno.h>           
#include <net/ethernet.h>    
#ifdef BSD
#else
#include <netinet/ether.h>
#endif
#include <net/if.h>
#include <arpa/inet.h>       
#include "arp.h"

#line 48 "ARP.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 192 "ARP.c"

XS_EUPXS(XS_Net__ARP_send_packet); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__ARP_send_packet)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "dev, sip, dip, smac, dmac, type");
    {
	const char *	dev = (const char *)SvPV_nolen(ST(0))
;
	const char *	sip = (const char *)SvPV_nolen(ST(1))
;
	const char *	dip = (const char *)SvPV_nolen(ST(2))
;
	const char *	smac = (const char *)SvPV_nolen(ST(3))
;
	const char *	dmac = (const char *)SvPV_nolen(ST(4))
;
	const char *	type = (const char *)SvPV_nolen(ST(5))
;
	int	RETVAL;
	dXSTARG;
#line 50 "ARP.xs"
	int uid;
	unsigned int packetsize = sizeof(struct my_arphdr) + sizeof(struct ether_header);
	unsigned char packet[packetsize];
	struct ether_header *ethhdr = (struct ether_header *)packet;
	struct my_arphdr *arp = (struct my_arphdr *)(packet + sizeof(struct ether_header));
	u_short op;	
	in_addr_t ipaddr;

	RETVAL = 1;

	// Are you root?
	uid = getuid();
	if(uid != 0) 
	{ 
		printf("You must have UID 0 instead of %d.\n", uid); 
		exit(0);
	}

	// Initialize packet buffer 
	memset(packet,0,packetsize);

	// What's the ARP operation type?
	if(!strcmp(type, "request"))
	{
		op = ARPOP_REQUEST;
	}
	else if(!strcmp(type, "reply"))
	{
		op = ARPOP_REPLY;
	}
	else if(!strcmp(type, "revrequest"))
	{
		op = ARPOP_REVREQUEST;
	}
	else if(!strcmp(type, "revreply"))
	{
		op = ARPOP_REVREPLY;
	}
	else if(!strcmp(type, "invrequest"))
	{
		op = ARPOP_INVREQUEST;
	}
	else if(!strcmp(type, "invreply"))
	{
		op = ARPOP_INVREPLY;
	}
	else
	{
		printf("Unknown ARP operation\n");
		RETVAL = 0;
	}

	if(smac == NULL)
	{
		printf("Parameter smac is NULL! Terminating.\n");
		RETVAL = 0;
	}

	if(dmac == NULL)
	{
		printf("Parameter dmac is NULL! Terminating.\n");
		RETVAL = 0;
	}

	// Found a dollar sign?
	if(strchr(smac, 36))
	{
		printf("Found a $ char in smac! Terminating.\n");
		RETVAL = 0;
	}

	if(strchr(dmac, 36))
	{
		printf("Found a $ char in dmac! Terminating.\n");
		RETVAL = 0;
	}

	if(ether_aton(smac) == NULL)
	{
		printf("Invalid source mac address! Terminating.\n");
		RETVAL = 0;
	}

	if(ether_aton(dmac) == NULL)
	{
		printf("Invalid destination mac address! Terminating.\n");
		RETVAL = 0;
	}

	// Check ips
	if(inet_addr(sip) == INADDR_NONE)
	{
		printf("Invalid source ip address! Terminating.\n");
		RETVAL = 0;
	}

	if(inet_addr(dip) == INADDR_NONE)
	{
		printf("Invalid destination ip address! Terminating.\n");
		RETVAL = 0;
	}

	// Construct and send packet
	if(RETVAL != 0)
	{
		// Ethernet header
		memcpy(ethhdr->ether_dhost,(u_char *)ether_aton(dmac), ETHER_ADDR_LEN); // Destination MAC
		memcpy(ethhdr->ether_shost,(u_char *)ether_aton(smac), ETHER_ADDR_LEN); // Source MAC
		ethhdr->ether_type = htons(ETHERTYPE_ARP);                              // ARP protocol

		// ARP header
		arp->hw_type = htons(ARPHDR_ETHER);                                     // Hardware address type
		arp->proto_type = htons(ETH_P_IP);                                      // Protocol address type
		arp->ha_len = ETH_ALEN;                                                 // Hardware address length
		arp->pa_len = IP_ALEN;                                                  // Protocol address length
		arp->opcode = htons(op);                                                // ARP operation
		memcpy(arp->source_add,(u_char *)ether_aton(smac), ETH_ALEN);           // Source MAC
		memcpy(arp->dest_add,(u_char *)ether_aton(dmac), ETH_ALEN);             // Destination MAC
		ipaddr = inet_addr(sip);
		memcpy(arp->source_ip, (u_char *)&ipaddr, IP_ALEN);        		        // Source IP

		ipaddr = inet_addr(dip);
		memcpy(arp->dest_ip, (u_char *)&ipaddr, IP_ALEN);	            	    // Destination IP


		if(LINUX == 1)
		{
			RETVAL = send_packet_linux(dev, packet, packetsize);	    
		}
		else
		{
			RETVAL = send_packet_bsd(dev, packet, packetsize);	
		}
	}

#line 351 "ARP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__ARP_get_mac); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__ARP_get_mac)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dev");
    {
	const char *	dev = (const char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;
#line 192 "ARP.xs"
    char tmp[HEX_HW_ADDR_LEN] = "unknown";

	if(LINUX == 1)
	{
		get_mac_linux(dev, tmp);
	}
	else
	{
		get_mac_bsd(dev, tmp);	  
	}

	RETVAL = tmp;

#line 383 "ARP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__ARP_arp_lookup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__ARP_arp_lookup)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dev, ip");
    {
	const char *	dev = (const char *)SvPV_nolen(ST(0))
;
	const char *	ip = (const char *)SvPV_nolen(ST(1))
;
	char *	RETVAL;
	dXSTARG;
#line 215 "ARP.xs"
	char tmp[HEX_HW_ADDR_LEN] = "unknown";

	if(LINUX == 1)
	{
		arp_lookup_linux(dev, ip, tmp);
	}
	else
	{
		arp_lookup_bsd(dev, ip, tmp);	
	}

	RETVAL = tmp;

#line 417 "ARP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Net__ARP); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Net__ARP)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Net::ARP::send_packet", XS_Net__ARP_send_packet);
        newXS_deffile("Net::ARP::get_mac", XS_Net__ARP_get_mac);
        newXS_deffile("Net::ARP::arp_lookup", XS_Net__ARP_arp_lookup);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

